### ISSUE TITLE
see below

### ISSUE THREAD

**Issue by xialang2012** [DURAARK/orthogen#1]
I have a textured mesh, whether I can use orthogen to get the orthophoto?

**Comment by ukrispel** [comment]
Hi, orthogen is used to create orthophotos given a spherical panorama and a proxy geometry, therefore it acts as a tool to create the textures given such panoramas.
If you want to create orthophotos from textured meshes you could use any rendering tool that supports orthographic projections, e.g. Blender.

**Comment by xialang2012** [comment]
thank you.
